-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.company
(
    cid "char"[] NOT NULL,
    cname "char"[] NOT NULL,
    clogo "char"[] NOT NULL,
    cdescription "char"[] NOT NULL,
    PRIMARY KEY (cid)
);

COMMENT ON TABLE public.company
    IS 'It Based Company';

CREATE TABLE IF NOT EXISTS public.departments
(
    did "char"[] NOT NULL,
    dname "char"[] NOT NULL,
    PRIMARY KEY (did)
);

COMMENT ON TABLE public.departments
    IS 'It Departments (Hr, IT,
Marketing......).';

CREATE TABLE IF NOT EXISTS public.employees
(
    eid "char"[] NOT NULL,
    dept_id "char"[] NOT NULL,
    ename "char"[] NOT NULL,
    email "char"[] NOT NULL,
    enumber "char"[] NOT NULL,
    PRIMARY KEY (eid)
);

COMMENT ON TABLE public.employees
    IS 'Company Employee Bio';

ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (dept_id)
    REFERENCES public.departments (did) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;